### ISSUE TITLE
It's not a problem, it's a question. :)

### ISSUE THREAD

**Issue by abeksis** [jimz011/homeassistant#1]
https://www.youtube.com/watch?v=AQwMQndGYuQ&t=6s

In your video - what themes do you use? I've added all of your themes and there's a lot.

Another question, under security - your headlines are captioned - however, in the photo I added, the headlines have a background.
![Screenshot_20190731-165914_Chrome](https://user-images.githubusercontent.com/10877299/62218281-cd381280-b3b4-11e9-8a3b-67346ce6b1b2.jpg)

**Comment by jimz011** [comment]
No problem, the themes I use are called Gray Homekit (I have a dark and a light version). For the headlines you will need the following cards: decluttering-card and card-mod (not card-modder!). Without these cards the code will not work. I assume you have the decluttering card already (as the buttons seem pretty much what I have created. But card-mod allows for styling. If you want to copy my config (or parts of it) I advise you to make sure to install all of the necessary custom-cards.

If you do not use decluttering-card you can do this as follows:
```
- type: markdown
  style: |
    ha-card {
      box-shadow: none;
      height: 33px;
      background: rgba(0,0,0,0.0);
      padding: 0px 10px;
    }
  content: 'YOUR HEADLINE HERE'
```
Remember that you NEED card-mod for this to work. If you use the older card-modder I would advise you to uninstall that and use card-mod instead (as they do the same thing, but card-mod is better as it isn't a card in itself but a modification to a core card, there is a markdown-mod as well, which I use in notifications). The reason to drop card-modder is simple, they both come from the same developer and the dev said he will deprecate card-modder in a few months.

Hope this helps you.

**Comment by abeksis** [comment]
thanks for the detailed answer.

In the picture above, you see the icons, the part of the icon escapes to the side (indicated by a red arrow). Plus there is a space below the icons (highlighted in blue)

![00](https://user-images.githubusercontent.com/10877299/62266987-352d3e00-b433-11e9-8a67-72c2df029d8c.jpg)

**Comment by jimz011** [comment]
I assume you use my button design. If so I’d suggest using only 3 or 4 buttons in a single row. They will scale nicely for different screensizes. But if you put more than 3 or 4 icons in a horizontal-stack the design has to be modified. Try with 3 buttons on a row first.

**Comment by abeksis** [comment]
thank you for the answer.

I did. But the second-line icons are big. Here's my code, what am I missing?

![Screenshot_20190801-174256_Chrome](https://user-images.githubusercontent.com/10877299/62302942-e9ef4b80-b483-11e9-8437-846636f62423.jpg)


`
      - type: custom:card-loader
        wait:
          - decluttering-card
          - button-card
        card:
          type: vertical-stack
          cards:
            - type: custom:decluttering-card
              template: header_text
              variables:
                - content: '##### Doors #####'
            - type: horizontal-stack
              cards:
                - type: 'custom:button-card'
                  color_type: blank-card
                  styles:
                    card:
                      - width: 10px
                      
                - type: custom:decluttering-card
                  template: switch_button_card
                  variables:
                    - entity: binary_sensor.door_window_sensor_158d0001ef3425
                    - name: Front Door
                    - icon: door
                    - show_last_changed: true
                    - tap_action: more-info
                    - variable: icon
                    - spin: 'mdi:door-open'

                - type: custom:decluttering-card
                  template: switch_button_card
                  variables:
                    - entity: binary_sensor.door_window_sensor_158d00027a59c6
                    - name: Balcony Door
                    - icon: door
                    - show_last_changed: true
                    - tap_action: more-info
                    - variable: icon
                    - spin: 'mdi:door-open'

                - type: custom:decluttering-card
                  template: switch_button_card
                  variables:
                    - entity: binary_sensor.door_window_sensor_158d0002ea0754
                    - name: Washing Machine
                    - icon: door
                    - show_last_changed: true
                    - tap_action: more-info
                    - variable: icon
                    - spin: 'mdi:door-open'
                - type: 'custom:button-card'
                  color_type: blank-card
                  styles:
                    card:
                      - width: 10px

            - type: horizontal-stack
              cards:
                - type: 'custom:button-card'
                  color_type: blank-card
                  styles:
                    card:
                      - width: 10px
                      
                - type: custom:decluttering-card
                  template: switch_button_card
                  variables:
                    - entity: binary_sensor.door_window_sensor_158d0002ea866a
                    - name: AC Yakir door
                    - icon: door
                    - show_last_changed: true
                    - tap_action: more-info
                    - variable: icon
                    - spin: 'mdi:door-open'
                - type: 'custom:button-card'
                  color_type: blank-card
                  styles:
                    card:
                      - width: 10px 
 
                - type: custom:decluttering-card
                  template: switch_button_card
                  variables:
                    - entity: binary_sensor.door_window_sensor_158d0002ea9896
                    - name: Laundry Dryer
                    - icon: door
                    - show_last_changed: true
                    - tap_action: more-info
                    - variable: icon
                    - spin: 'mdi:door-open'

                - type: 'custom:button-card'
                  color_type: blank-card
                  styles:
                    card:
                      - width: 10px                   
    
            - type: custom:decluttering-card
              template: header_text
              variables:
                - content: '##### Motion ####'

            - type: horizontal-stack
              cards:
                - type: 'custom:button-card'
                  color_type: blank-card
                  styles:
                    card:
                      - width: 10px

                - type: custom:decluttering-card
                  template: switch_button_card
                  variables:
                    - entity: binary_sensor.motion_sensor_158d0002047c5a
                    - name: Shower
                    - icon: motion-sensor
                    - show_last_changed: true
                    - tap_action: more-info

                - type: custom:decluttering-card
                  template: switch_button_card
                  variables:
                    - entity: binary_sensor.motion_sensor_158d00024e7972
                    - name: Laundry
                    - icon: motion-sensor
                    - show_last_changed: true
                    - tap_action: more-info

                - type: custom:decluttering-card
                  template: switch_button_card
                  variables:
                    - entity: binary_sensor.motion_sensor_158d000204bfcb
                    - name: Parents
                    - icon: motion-sensor
                    - show_last_changed: true
                    - tap_action: more-info


                - type: custom:decluttering-card
                  template: switch_button_card
                  variables:
                    - entity: binary_sensor.motion_sensor_158d000272bc63
                    - name: Server Room
                    - icon: motion-sensor
                    - show_last_changed: true
                    - tap_action: more-info
                - type: 'custom:button-card'
                  color_type: blank-card
                  styles:
                    card:
                      - width: 10px  

                - type: custom:decluttering-card
                  template: switch_button_card
                  variables:
                    - entity: binary_sensor.motion_sensor_158d0002b42fa3
                    - name: Guests Bbathroom
                    - icon: motion-sensor
                    - show_last_changed: true
                    - tap_action: more-info

                - type: 'custom:button-card'
                  color_type: blank-card
                  styles:
                    card:
                      - width: 10px


            - type: custom:decluttering-card
              template: header_text
              variables:
                - content: '##### Alarms #####'
            - type: horizontal-stack
              cards:
                - type: 'custom:button-card'
                  color_type: blank-card
                  styles:
                    card:
                      - width: 10px
                - type: custom:decluttering-card
                  template: switch_button_card
                  variables:
                    - entity: binary_sensor.smoke_sensor_158d00028ee7fb
                    - name: Kitchen
                    - icon: smoke-detector
                    - show_last_changed: true
                    - tap_action: more-info
                - type: 'custom:button-card'
                  color_type: blank-card
                  aspect_ratio: 1/1
                - type: 'custom:button-card'
                  color_type: blank-card
                  aspect_ratio: 1/1
                - type: 'custom:button-card'
                  color_type: blank-card
                  styles:
                    card:
                      - width: 10px
            - type: 'custom:button-card'
              color_type: blank-card
              styles:
                card:
                - height: 10px                    

#`

**Comment by abeksis** [comment]
Did the job :)   

I saw that you are using Slide right and left .. What's the name of the plugin?

```
             ### Space ##
                - type: custom:gap-card
                  height: 100

```

**Comment by jimz011** [comment]
I don’t use gap-card. I just used a blank card instead with an aspect_ratio of 1/1. For an example see my light.yaml or devices.yaml file. It is the same button-card I use in most of my setup.

If you want to swipe between views you will either need lovelace-swipe-navigation or compact-custom-header. The last one is linked in the readme file on this repo.

**Comment by jimz011** [comment]
I will add the missing wallpapers later

**Comment by abeksis** [comment]
I have a problem with a vacuum popup.

In the photo, you can see all the files I copied from you, which belongs to the robot.
The icon in lovelace is active, but there is no popup

<img width="1020" alt="Screen Shot 2019-08-02 at 13 18 33" src="https://user-images.githubusercontent.com/10877299/62363527-3a1fe980-b528-11e9-9125-1952294f0548.png">

**Comment by jimz011** [comment]
This discussion has continued on discord. I will close this issue now.
