### ISSUE TITLE
secret!

### ISSUE THREAD

**Issue by metbril** [jimz011/homeassistant#10]
https://github.com/jimz011/homeassistant/blob/f491687468116686f10d498f0fcf50d3c1d90138/configuration/sensor/rdw-sensors.yaml#L6

you should move those to a secret.

**Comment by jimz011** [comment]
I understand your concern, but really license plate information is freely available at RDW. So not a big concern. Also, when I drive outside everyone can see the license plate 😂☺️. Thanks for your concern though. It’s appreciated.

**Comment by jimz011** [comment]
Addition: also most of the stuff you find on my repo are not real and just some random numbers and letters.
