### ISSUE TITLE
HKI V1.1 Home Button and Menu Button Laggy

### ISSUE THREAD

**Issue by MagicMountainMan** [jimz011/homeassistant#13]
To preface, I use Android and my roommate uses an iPhone.

The issue:
Pressing the home button or the menu button on the lower right often requires a double press. The first press will cause the navigation line indicator to appear under the button, but then only after the second press will it actually navigate to home or menu.

This happens much more often on my Android phone (Google Pixel 2XL) than on my roommate's iPhone (11 Pro Max), however it does happen on both occasionally.

Perhaps this is a Custom Header issue?

**Comment by jimz011** [comment]
Unfortunately this is indeed Custom Header. It is also the reason why I have minimized the use of CH to only those 2 buttons. At first I have made it entirely with CH, but the performance would suffer way too much. This was kinda acceptable and currently the only known way yo have footers. This may or may not be addressed in the future but it depends on the creator(s) of CH.

**Comment by MagicMountainMan** [comment]
Ah that's unfortunate but kind of what I expected. Hopefully the dev finds a way to enhance performance.
