### ISSUE TITLE
[FR] Add Global Font Size Variables

### ISSUE THREAD

**Issue by MagicMountainMan** [jimz011/homeassistant#19]
Adding a global font size variable for names, states, labels, etc and exposing them to the front end would allow for quick style customization for people choosing between a 3 or 4 column view.

Ex: I could set the name font as 14pt, state font as 11pt, and label font as 13pt in the UI

It might be best to split it into variables for the 3 column views vs the 4 column views as the buttons become a different size depending on how many different columns are in use.

Ex: I want 3 Column Name Font as 14pt, but 4 Column Name Font as 12pt

**Comment by jimz011** [comment]
Added in beta 5 (only buttons can be changed for now, though that is almost all you'd ever need)
