### ISSUE TITLE
One more idea that I use!

### ISSUE THREAD

**Issue by xMrVizzy** [jimz011/homeassistant#4]
In ui-lovelace.yaml you can use this:
`decluttering_templates: !include_dir_named lovelace/templates`

And in lovelace/templates folder simply name files that you want it to be used in decluttering-card template.
![D993A609-4B5F-4E95-8DB6-1C8BE26F4BE8](https://user-images.githubusercontent.com/7906418/63582640-e2b6eb80-c5b2-11e9-8a57-0b0394e3ac32.png)

**Comment by xMrVizzy** [comment]
It’s more easy and no need to make 2 different names and create decluttering-templates.yaml file

**Comment by jimz011** [comment]
A great idea. Once I have the time again I will take a look at this.

Though where does it get the template name from to use in variables? Or do you set the name in each file at the top?

**Comment by jimz011** [comment]
Lol you are Mars Warrior right? I didn’t even notice until I saw your logo XD. At least now I know how to properly thank you!

**Comment by xMrVizzy** [comment]
The name of the template is a name of File.

From HomeAssistant site:
!include_dir_named will return the content of a directory as a dictionary which maps filename => content of file.

**Comment by xMrVizzy** [comment]
Example:
![40CD0EF6-049D-4C1C-9A4D-18F53C5BC5C3](https://user-images.githubusercontent.com/7906418/63635440-101b9c00-c67c-11e9-9a7a-abc66a7c57d5.png)
![59F4B662-7D5A-481E-A827-FC3EC86BD3DB](https://user-images.githubusercontent.com/7906418/63635441-101b9c00-c67c-11e9-8d96-a6f052656fdc.png)

I named energy-usage as it should use in template, and the file completely yours without changes.

**Comment by jimz011** [comment]
Thank you, I will close this issue. Implemented in 0.12.3
