### ISSUE TITLE
Frontpage Developer Tools Link Fix

### ISSUE THREAD

**Issue by nightcat91** [jimz011/homeassistant#5]
Hi,

I found a small bug in the 0.12.3 update.
The change in the frontpage to include the link to developer tools page does not work.
https://github.com/jimz011/homeassistant/blob/master/lovelace/views/frontpage.yaml#L23
It comes out at this url: "http://ip:8123/lovelace/developer-tools"  which does not work....

I changed it to 
- path1: ../developer-tools

You could also go for 
- path1: ../developer-tools/state
to get to the states screen direcctly if you like that.

**Comment by jimz011** [comment]
Thanks, this is a known issue to me. They are remnants of a testpage. You can just remove the line from ui-lovelace.yaml for now. I will be adding them back in another update.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
