### ISSUE TITLE
Update Guide 0.12.3 Additional Info (missing tags)

### ISSUE THREAD

**Issue by nightcat91** [jimz011/homeassistant#6]
Hi,

just to let you know in some of the files you missed adding the # Changed/Added in 0.12.3 tag,

This includes the following files (might be more, those are the ones I found while using the guide to update):
frontpage.yaml
sensor.yaml

Thanks for your great work, keep it up, really good lovelace setup!!

**Comment by jimz011** [comment]
Thank you, it was probably a lot to add so I probably have put it in the guide instead. Thanks for sending this. I will keep an eye out for this in the next updates.

Also the old files are still present (the old templates) these will be removed in 0.13.0. The next update will be a major one which will finally include the long promised CSS update!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
