### ISSUE TITLE
Remove your secret

### ISSUE THREAD

**Issue by bruvv** [jimz011/homeassistant#9]
Not sure why you would upload your secret file because that is the whole idea of the secret file that you do not need to upload that ... There are phone numbers in there and API keys that can be abused.

**Comment by jimz011** [comment]
Trust me, there are none :P

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bruvv** [comment]
haha het was nog vroeg.. no worries ik close :)

**Comment by jimz011** [comment]
I really thank you for your concern, but none of those secrets are actually real. Take a look at the phone numbers for one. All secrets are just random stuff so that people have an example of what they need to do.

Still thanks though.

**Comment by jimz011** [comment]
Geen probleem, krijg dit soort berichten wel vaker. Maar de secrets zijn allemaal nep 🤣😂.

**Comment by CCOSTAN** [comment]
As an alternative @jimz011 , you can also use Travis-secrets.yaml for examples. 

https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/travis_secrets.yaml

**Comment by jimz011** [comment]
I just don’t see why someone elses secrets file could be relevant to this config?

The secret file I include is for good reason, as lovelace will not load if there are unknown secrets or unspecified ones. This way whatever you do, as long as you download/copy the secrets file, lovelace will load (even if the entity doesn’t exist).
